name: Compile and release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Download AutoHotkey
      run: Start-BitsTransfer -Source https://autohotkey.com/download/ahk.zip -Destination ahk.zip
    - name: Extract AutoHotkey
      run: Expand-Archive -Path ahk.zip -DestinationPath ahk
    - name: Compile
      run: ./ahk/Compiler/Ahk2Exe.exe /in main.ahk /out VolumeCtrl.exe /icon icon-blue.ico
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: All changes for release ${{ github.run_number }}...
    - name: Add exe to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: VolumeCtrl.exe
        asset_name: VolumeCtrl.exe
        asset_content_type: application/octet-stream
